version: "3"
services:
  browserless:
    image: ghcr.io/browserless/chromium
    environment:
      TOKEN: your_secret_token
      MAX_CONCURRENT_SESSIONS: 5
    ports:
      - "3002:3002"

  api:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - browserless