Set-Location $PSScriptRoot
Write-Host "Running gofmt..."
go fmt ./...
Write-Host "Running tests..."
go test ./...
Write-Host "Building binary..."
go build ./...
Write-Host "Pre-deploy checks completed successfully."
